from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from app.main import app


ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "packages" / "contracts" / "openapi.json"
TYPES_PATH = ROOT / "apps" / "web" / "app" / "types" / "api-contract.ts"
JSON_TYPE_MAP = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated contract files are out of date.")
    args = parser.parse_args()

    schema = app.openapi()
    openapi_text = json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    types_text = render_types(schema)

    if args.check:
        stale = []
        if not OPENAPI_PATH.exists() or OPENAPI_PATH.read_text(encoding="utf-8") != openapi_text:
            stale.append(str(OPENAPI_PATH.relative_to(ROOT)))
        if not TYPES_PATH.exists() or TYPES_PATH.read_text(encoding="utf-8") != types_text:
            stale.append(str(TYPES_PATH.relative_to(ROOT)))
        if stale:
            print("OpenAPI contract is out of date: " + ", ".join(stale), file=sys.stderr)
            print("Run `npm run contracts:generate`.", file=sys.stderr)
            return 1
        return 0

    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPES_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(openapi_text, encoding="utf-8")
    TYPES_PATH.write_text(types_text, encoding="utf-8")
    print(f"Wrote {OPENAPI_PATH.relative_to(ROOT)}")
    print(f"Wrote {TYPES_PATH.relative_to(ROOT)}")
    return 0


def render_types(openapi: dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_openapi_contract.py. Do not edit by hand.",
        "",
    ]
    for name in sorted(schemas):
        lines.append(f"export type {safe_type_name(name)} = {schema_to_ts(schemas[name], schemas)};")
        lines.append("")
    lines.append("export type ApiPaths = {")
    for path in sorted(openapi.get("paths", {})):
        path_item = openapi["paths"][path]
        method_lines = []
        for method in ["get", "post", "patch", "put", "delete"]:
            if method not in path_item:
                continue
            operation = path_item[method]
            response_type = response_ts(operation, schemas)
            request_type = request_ts(operation, schemas)
            if not response_type and not request_type:
                continue
            parts = []
            if request_type:
                parts.append(f"request: {request_type}")
            if response_type:
                parts.append(f"response: {response_type}")
            method_lines.append(f"    {method}: {{ {'; '.join(parts)} }};")
        if not method_lines:
            continue
        lines.append(f"  {json.dumps(path, ensure_ascii=False)}: {{")
        lines.extend(method_lines)
        lines.append("  };")
    lines.append("};")
    lines.append("")
    lines.append("export type ApiResponse<Path extends keyof ApiPaths, Method extends keyof ApiPaths[Path]> =")
    lines.append("  ApiPaths[Path][Method] extends { response: infer Response } ? Response : never;")
    lines.append("")
    lines.append("export type ApiRequest<Path extends keyof ApiPaths, Method extends keyof ApiPaths[Path]> =")
    lines.append("  ApiPaths[Path][Method] extends { request: infer Request } ? Request : never;")
    lines.append("")
    return "\n".join(lines)


def response_ts(operation: dict[str, Any], schemas: dict[str, Any]) -> str | None:
    for status in ["200", "201", "202", "204", "default"]:
        response = operation.get("responses", {}).get(status)
        if not response:
            continue
        content = response.get("content", {}).get("application/json")
        if not content:
            continue
        return schema_to_ts(content.get("schema", {}), schemas)
    return None


def request_ts(operation: dict[str, Any], schemas: dict[str, Any]) -> str | None:
    content = operation.get("requestBody", {}).get("content", {}).get("application/json")
    if not content:
        return None
    return schema_to_ts(content.get("schema", {}), schemas)


def schema_to_ts(schema: dict[str, Any], schemas: dict[str, Any]) -> str:
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return safe_type_name(schema["$ref"].rsplit("/", 1)[-1])
    if "allOf" in schema:
        return " & ".join(schema_to_ts(item, schemas) for item in schema["allOf"])
    if "anyOf" in schema:
        return " | ".join(dedupe(schema_to_ts(item, schemas) for item in schema["anyOf"]))
    if "oneOf" in schema:
        return " | ".join(dedupe(schema_to_ts(item, schemas) for item in schema["oneOf"]))
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(dedupe(JSON_TYPE_MAP.get(item, "unknown") for item in schema_type))
    if schema_type == "array":
        item_type = schema_to_ts(schema.get("items", {}), schemas)
        if " | " in item_type or " & " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        additional = schema.get("additionalProperties")
        if not properties and additional:
            value_type = schema_to_ts(additional if isinstance(additional, dict) else {}, schemas)
            return f"Record<string, {value_type}>"
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = []
        for key, value in properties.items():
            optional = "" if key in required else "?"
            fields.append(f"{quote_key(key)}{optional}: {schema_to_ts(value, schemas)}")
        return "{ " + "; ".join(fields) + " }"
    return JSON_TYPE_MAP.get(str(schema_type), "unknown")


def quote_key(key: str) -> str:
    return key if key.replace("_", "").isalnum() and not key[0].isdigit() else json.dumps(key, ensure_ascii=False)


def safe_type_name(name: str) -> str:
    return "".join(part if part.isalnum() else "_" for part in name)


def dedupe(items: Any) -> list[str]:
    result = []
    for item in items:
        if item not in result:
            result.append(item)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
