/* eslint-disable */
// Generated by scripts/generate_openapi_contract.py. Do not edit by hand.

export type AdminOrderEnvelope = { order: AdminOrderOut };

export type AdminOrderOut = { id: string; orderNumber: string; customerName: string; contact: string; serviceSlug: string; category: string; title: string; demand: string; originalDemand: string; polishedDemand: string; urgency: string; budget: string; remoteHelp: string; intent: string; missingFields: string[]; serviceConfidence: number; quotedPrice: number | null; status: string; aiStatus: string; nextAction: string; publicNotes: string; createdAt: string; updatedAt: string; events: OrderEventOut[]; messages: OrderMessageOut[]; attachments: OrderAttachmentOut[]; quotes: QuoteOut[]; payments: PaymentRecordOut[]; deliverables: DeliverableOut[]; ownerUserId: string | null; cost: number | null; profit: number | null; priority: string; internalNotes: string; assignedAdminId: string | null; automationAuditCount: number; automationSuggestions: AutomationSuggestionOut[]; todos: OrderTodoOut[]; aiSummaries: OrderAiSummaryOut[] };

export type AdminOrderPatch = { status?: string | null; priority?: string | null; quotedPrice?: number | null; cost?: number | null; profit?: number | null; publicNotes?: string | null; internalNotes?: string | null; nextAction?: string | null };

export type AdminOrdersOut = { orders: AdminOrderOut[]; pagination: PaginationOut };

export type AgentActionOut = { label: string; to: string };

export type AgentChatInput = { sessionId: string; message: string };

export type AgentChatOut = { answer: string; actions: AgentActionOut[]; citations?: AgentCitationOut[]; draft?: AgentDraftOut | null };

export type AgentCitationOut = { title: string; to: string; source?: string | null };

export type AgentDraftOut = { serviceSlug: string; summary: string; missingFields: string[] };

export type AgentSessionEnvelope = { session: AgentSessionOut };

export type AgentSessionInput = { visitorId?: string | null; pagePath?: string };

export type AgentSessionOut = { id: string; pagePath: string; userId: string | null };

export type AssistantSummaryContentOut = { orderNumber: string; status: string; nextAction: string; publicNotes: string };

export type AssistantSummaryOut = { summary: AssistantSummaryContentOut };

export type AttachmentDownloadEnvelope = { download: AttachmentDownloadOut };

export type AttachmentDownloadOut = { provider: string; bucket: string; objectKey: string; downloadUrl: string; expiresIn: number };

export type AttachmentInput = { fileName: string; fileSize: number; contentType: string; storageKey: string; bucket?: string; checksum?: string };

export type AuthIn = { email: string; password: string };

export type AuthOut = { token: string; user: UserOut };

export type AutomationSuggestionOut = { id: string; kind: string; severity: string; summary: string; suggestedStatus: string | null; suggestedMessage: string; confidence: number; status: string; reason: string; createdAt: string };

export type DeliverableInput = { title: string; description?: string; storageKey: string };

export type DeliverableOut = { id: string; title: string; description: string; storageKey: string; createdAt: string };

export type DependencyHealthOut = { ok: boolean; required: boolean; status: string; detail?: string | null; driver?: string | null; provider?: string | null; model?: string | null; articleCount?: number | null; chunkCount?: number | null; embeddingCount?: number | null };

export type DocAnchorOut = { id: string; title: string; level: number };

export type DocDetailOut = { slug: string; title: string; category: string; description: string; tags: string[]; order: number; updatedAt: string; status: string; content: string; anchors: DocAnchorOut[]; relatedDocs: DocSummaryOut[] };

export type DocEnvelope = { doc: DocDetailOut };

export type DocSearchOut = { results: DocSearchResultOut[] };

export type DocSearchResultOut = { slug: string; title: string; excerpt: string; anchor?: string | null };

export type DocSummaryOut = { slug: string; title: string; category: string; description: string; tags: string[]; order: number; updatedAt: string; status: string };

export type DocsOut = { docs: DocSummaryOut[] };

export type HTTPValidationError = { detail?: ValidationError[] };

export type HealthDepsOut = { ok: boolean; service: string; version: string; environment: string; dependencies: Record<string, DependencyHealthOut> };

export type HealthOut = { ok: boolean; service: string; version: string };

export type KnowledgeArticleOut = { id: string; scope: string; title: string; body: string; tags: string[]; source: string; updatedAt: string };

export type KnowledgeArticlesOut = { articles: KnowledgeArticleOut[] };

export type MessageInput = { body: string; visibility?: string };

export type NoteInput = { serviceSlug?: string | null; demand: string; originalDemand?: string | null; category?: string; urgency?: string; budget?: string; contact: string; remoteHelp?: string; customerName?: string | null; intent?: string | null };

export type NotificationEnvelope = { notification: NotificationOut };

export type NotificationOut = { id: string; type: string; orderNumber: string | null; title: string; body: string; status: string; targetUrl: string; createdAt: string; readAt: string | null };

export type NotificationUnreadCountOut = { unreadCount: number };

export type NotificationsOut = { notifications: NotificationOut[] };

export type NotificationsReadAllOut = { updated: number };

export type OrderAiSummaryOut = { id: string; summary: string; riskFlags: string[]; suggestedQuestions: string[]; createdAt: string };

export type OrderAttachmentOut = { id: string; fileName: string; fileSize: number; contentType: string; bucket: string; storageKey: string; visibility: string; scanStatus: string; parsedSummary: string; scanError: string; retryCount: number; lastScannedAt: string | null; createdAt: string };

export type OrderEnvelope = { order: OrderOut };

export type OrderEventOut = { id: string; status: string; note: string; createdBy: string | null; createdAt: string };

export type OrderMessageOut = { id: string; authorUserId: string; body: string; visibility: string; createdAt: string };

export type OrderOut = { id: string; orderNumber: string; customerName: string; contact: string; serviceSlug: string; category: string; title: string; demand: string; originalDemand: string; polishedDemand: string; urgency: string; budget: string; remoteHelp: string; intent: string; missingFields: string[]; serviceConfidence: number; quotedPrice: number | null; status: string; aiStatus: string; nextAction: string; publicNotes: string; createdAt: string; updatedAt: string; events: OrderEventOut[]; messages: OrderMessageOut[]; attachments: OrderAttachmentOut[]; quotes: QuoteOut[]; payments: PaymentRecordOut[]; deliverables: DeliverableOut[] };

export type OrderTodoOut = { id: string; title: string; source: string; status: string; dueAt: string | null; createdAt: string };

export type OrdersOut = { orders: OrderOut[] };

export type PaginationOut = { page: number; pageSize: number; total: number; hasMore: boolean };

export type PasswordResetConfirmIn = { token: string; password: string };

export type PasswordResetRequestIn = { email: string };

export type PaymentInput = { amount: number; kind: string; method: string; status: string; note?: string };

export type PaymentRecordOut = { id: string; amount: number; kind: string; method: string; status: string; note: string; createdAt: string };

export type PolishInput = { demand: string; serviceSlug?: string | null };

export type PolishOut = { polishedDemand: string; hints: string[]; intent: string; missingFields: string[]; serviceConfidence: number };

export type PresignedUploadEnvelope = { upload: PresignedUploadOut };

export type PresignedUploadOut = { provider: string; bucket: string; objectKey: string; uploadUrl: string; publicUrl: string | null; fields: Record<string, string> };

export type QuoteInput = { amount: number; kind?: string; note: string };

export type QuoteOut = { id: string; amount: number; kind: string; note: string; status: string; createdAt: string };

export type RegisterIn = { email: string; password: string; displayName: string; referralCode?: string | null };

export type ServiceEnvelope = { service: ServiceOut };

export type ServiceOut = { slug: string; title: string; tag: string; summary: string; audience: string[]; commonNeeds: string[]; deliverables: string[]; requiredMaterials: string[]; priceRange: string; timeline: string; risks: string[]; cases: Record<string, string>[]; faq: Record<string, string>[] };

export type ServicesOut = { services: ServiceOut[] };

export type StatusOut = { ok: boolean; message: string };

export type TokenConfirmIn = { token: string };

export type UploadPresignInput = { fileName: string; fileSize: number; contentType: string; orderNumber?: string | null };

export type UserEnvelope = { user: UserOut };

export type UserOut = { id: string; email: string; role: string; displayName: string };

export type UserProfileEnvelope = { profile: UserProfileOut };

export type UserProfileOut = { id: string; email: string; role: string; displayName: string; points: number; referralCode: string; referredByUserId: string | null; emailVerifiedAt: string | null; createdAt: string };

export type UserProfilePatch = { displayName: string };

export type UserReferralEnvelope = { referral: Record<string, unknown> };

export type UserSummaryEnvelope = { summary: Record<string, unknown> };

export type ValidationError = { loc: (string | number)[]; msg: string; type: string; input?: unknown; ctx?: Record<string, unknown> };

export type ApiPaths = {
  "/api/admin/orders": {
    get: { response: AdminOrdersOut };
  };
  "/api/admin/orders/{order_number}": {
    get: { response: AdminOrderEnvelope };
    patch: { request: AdminOrderPatch; response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/attachments/{attachment_id}/retry-scan": {
    post: { response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/automation/run": {
    post: { response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/deliverables": {
    post: { request: DeliverableInput; response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/messages": {
    post: { request: MessageInput; response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/payments": {
    post: { request: PaymentInput; response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/quotes": {
    post: { request: QuoteInput; response: AdminOrderEnvelope };
  };
  "/api/admin/orders/{order_number}/suggestions/{suggestion_id}/apply": {
    post: { response: AdminOrderEnvelope };
  };
  "/api/agent/chat": {
    post: { request: AgentChatInput; response: AgentChatOut };
  };
  "/api/agent/sessions": {
    post: { request: AgentSessionInput; response: AgentSessionEnvelope };
  };
  "/api/ai/polish-demand": {
    post: { request: PolishInput; response: PolishOut };
  };
  "/api/auth/email-verification/confirm": {
    post: { request: TokenConfirmIn; response: StatusOut };
  };
  "/api/auth/email-verification/request": {
    post: { response: StatusOut };
  };
  "/api/auth/login": {
    post: { request: AuthIn; response: AuthOut };
  };
  "/api/auth/me": {
    get: { response: UserEnvelope };
  };
  "/api/auth/password-reset/confirm": {
    post: { request: PasswordResetConfirmIn; response: StatusOut };
  };
  "/api/auth/password-reset/request": {
    post: { request: PasswordResetRequestIn; response: StatusOut };
  };
  "/api/auth/register": {
    post: { request: RegisterIn; response: AuthOut };
  };
  "/api/docs": {
    get: { response: DocsOut };
  };
  "/api/docs/search": {
    get: { response: DocSearchOut };
  };
  "/api/docs/{slug}": {
    get: { response: DocEnvelope };
  };
  "/api/health": {
    get: { response: HealthOut };
  };
  "/api/health/deps": {
    get: { response: HealthDepsOut };
  };
  "/api/inquiries": {
    post: { request: NoteInput; response: OrderEnvelope };
  };
  "/api/knowledge": {
    get: { response: KnowledgeArticlesOut };
  };
  "/api/knowledge/search": {
    get: { response: KnowledgeArticlesOut };
  };
  "/api/me/profile": {
    get: { response: UserProfileEnvelope };
    patch: { request: UserProfilePatch; response: UserProfileEnvelope };
  };
  "/api/me/referral": {
    get: { response: UserReferralEnvelope };
  };
  "/api/me/summary": {
    get: { response: UserSummaryEnvelope };
  };
  "/api/notifications": {
    get: { response: NotificationsOut };
  };
  "/api/notifications/read-all": {
    patch: { response: NotificationsReadAllOut };
  };
  "/api/notifications/unread-count": {
    get: { response: NotificationUnreadCountOut };
  };
  "/api/notifications/{notification_id}/read": {
    patch: { response: NotificationEnvelope };
  };
  "/api/orders": {
    get: { response: OrdersOut };
    post: { request: NoteInput; response: OrderEnvelope };
  };
  "/api/orders/{order_number}": {
    get: { response: OrderEnvelope };
  };
  "/api/orders/{order_number}/accept": {
    post: { response: OrderEnvelope };
  };
  "/api/orders/{order_number}/assistant-summary": {
    get: { response: AssistantSummaryOut };
  };
  "/api/orders/{order_number}/attachments": {
    post: { request: AttachmentInput; response: OrderEnvelope };
  };
  "/api/orders/{order_number}/attachments/{attachment_id}/download": {
    get: { response: AttachmentDownloadEnvelope };
  };
  "/api/orders/{order_number}/messages": {
    post: { request: MessageInput; response: OrderEnvelope };
  };
  "/api/public/inquiries": {
    post: { request: NoteInput; response: OrderEnvelope };
  };
  "/api/services": {
    get: { response: ServicesOut };
  };
  "/api/services/{slug}": {
    get: { response: ServiceEnvelope };
  };
  "/api/uploads/local/{object_key}": {
    get: { response: unknown };
  };
  "/api/uploads/presign": {
    post: { request: UploadPresignInput; response: PresignedUploadEnvelope };
  };
  "/health": {
    get: { response: HealthOut };
  };
};

export type ApiResponse<Path extends keyof ApiPaths, Method extends keyof ApiPaths[Path]> =
  ApiPaths[Path][Method] extends { response: infer Response } ? Response : never;

export type ApiRequest<Path extends keyof ApiPaths, Method extends keyof ApiPaths[Path]> =
  ApiPaths[Path][Method] extends { request: infer Request } ? Request : never;
